import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/contexts/ThemeContext";
import Header from "@/components/Header";
import ThemeStyleInjector from "@/components/ThemeStyleInjector";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrainsMono"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <ThemeStyleInjector />
      </head>
      <body className={jetbrainsMono.className}>
      <ThemeProvider>
          <>
            <Header />
            {children}
          </>
        </ThemeProvider>
      </body>
    </html>
  );
}