import { JetBrains_Mono, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/contexts/ThemeContext";
import Header from "@/components/Header";
import PageTransition from "@/components/transitions/PageTransition";
import ThemeStyleInjector from "@/components/ThemeStyleInjector";
import StairTransition from "@/components/transitions/StairTransition";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrainsMono"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-robotoMono",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <ThemeStyleInjector />
      </head>
      <body className={robotoMono.className}>
        <ThemeProvider>
          <>
            <Header />
            <StairTransition />
            <PageTransition>{children}</PageTransition>
          </>
        </ThemeProvider>
      </body>
    </html>
  );
}